### ISSUE TITLE
Create the means to define arrays

### ISSUE THREAD

**Issue by naweedanwari** [talhakhalil0703/CodeDoodle#13]
Make arrays portable, able to select their type (perhaps from the side bar) as well as their size. Arrays can also be n dimensional, where n is some positive integer, this needs to be accounted for as well. The design is not specified for this, and this element should be designed as it is created, with an emphasis on making sure users can define every type of array they would want to in C++/C. Perhaps dimensions and size can be defined after they drop it onto a stack frame. Or perhaps they should design it ahead of time.

**It is important that firstly some design work goes into this and is first approved before any code is started.**

**Comment by talhakhalil0703** [comment]
Make portable thing, make it scrollable, and ensure its draggable

**Comment by talhakhalil0703** [comment]
Number of dimensions, one object all the information of the array, data type, etc
